// <auto-generated />
using System;
using Booking.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Api.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking.Api.Models.PostoPrenotato", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IDPosto")
                        .HasColumnType("int");

                    b.Property<int>("IDPrenotazione")
                        .HasColumnType("int");

                    b.Property<int>("IDSpettacolo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDPrenotazione");

                    b.HasIndex("IDSpettacolo", "IDPosto")
                        .IsUnique();

                    b.ToTable("PostiPrenotati");
                });

            modelBuilder.Entity("Booking.Api.Models.Prenotazione", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDSpettacolo")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("Booking.Api.Models.PostoPrenotato", b =>
                {
                    b.HasOne("Booking.Api.Models.Prenotazione", "Prenotazione")
                        .WithMany("Posti")
                        .HasForeignKey("IDPrenotazione")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("Booking.Api.Models.Prenotazione", b =>
                {
                    b.Navigation("Posti");
                });
#pragma warning restore 612, 618
        }
    }
}
