// <auto-generated />
using System;
using Catalog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260825144422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Api.Models.Posto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IDSala")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDSala", "Fila", "Numero")
                        .IsUnique();

                    b.ToTable("Posti");
                });

            modelBuilder.Entity("Catalog.Api.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Catalog.Api.Models.Spettacolo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDSala")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDSala");

                    b.ToTable("Spettacoli");
                });

            modelBuilder.Entity("Catalog.Api.Models.Posto", b =>
                {
                    b.HasOne("Catalog.Api.Models.Sala", "Sala")
                        .WithMany("Posti")
                        .HasForeignKey("IDSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Catalog.Api.Models.Spettacolo", b =>
                {
                    b.HasOne("Catalog.Api.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("IDSala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Catalog.Api.Models.Sala", b =>
                {
                    b.Navigation("Posti");
                });
#pragma warning restore 612, 618
        }
    }
}
